name: Compile python requirements and create PR
on:
  push:
    branches:
      - main
  workflow_dispatch:

  schedule:
    - cron: "5 6 * * 1-5" # At 06:05 on every day-of-week from Monday through Friday

permissions:
  contents: write
  pull-requests: write

jobs:
  compile-requirements-and-create-pr:
    permissions:
      contents: write
      pull-requests: write
    uses: equinor/armada/.github/workflows/compile_python_requirements_and_create_pr.yml@main
