name: Deploy to Development

concurrency:
  group: development-concurrency
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - "main"

jobs:
  get-short-sha:
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - id: get-tag
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-8)
          echo "tag=$SHA_SHORT" >> "$GITHUB_OUTPUT"

  build-and-push-dev-image-to-robotics-dev-registry:
    name: Build and push dev image to robotics dev container registry
    needs: get-short-sha
    uses: equinor/armada/.github/workflows/build_and_publish_docker_image_to_container_registry.yml@main
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      registry: roboticsdevacr.azurecr.io
      image_name: robotics/isar-robot
      tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      secondary_tag: dev
      push_to_ghcr: true
      path_to_dockerfile: Dockerfile
      path_to_context: .
      environment: Development
      use_oidc: true
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    secrets:
      registry_password: ${{ secrets.ROBOTICS_ROBOTICSDEVACR_PASSWORD }}
      registry_username: ${{ secrets.ROBOTICS_ROBOTICSDEVACR_USERNAME }}

  deploy:
    name: Update deployment in Development
    needs: [build-and-push-dev-image-to-robotics-dev-registry, get-short-sha]
    uses: equinor/armada/.github/workflows/update_kubernetes_deployment.yml@main
    with:
      environment: development
      registry: roboticsdevacr.azurecr.io
      image_name: robotics/isar-robot
      tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      author_email: ${{ github.event.head_commit.author.email }}
      author_name: ${{ github.event.head_commit.author.name }}
      infrastructure_repository: equinor/robotics-infrastructure
      kustomization_base_path: k8s_kustomize/robotics/overlays
    secrets:
      deploy_key: ${{ secrets.ROBOTICS_INFRASTRUCTURE_DEPLOY_KEY }}
