name: Deploy to Staging

concurrency:
  group: staging-concurrency
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]

jobs:
  build-and-push-latest-release-image-to-robotics-staging-registry:
    name: Build and push latest release image to robotics staging registry
    uses: equinor/armada/.github/workflows/build_and_publish_docker_image_to_container_registry.yml@main
    permissions:
      contents: read
    with:
      registry: roboticsstagingacr.azurecr.io
      image_name: robotics/isar-robot
      tag: "${{ github.event.release.tag_name }}"
      secondary_tag: latest
      path_to_dockerfile: Dockerfile
      path_to_context: .
    secrets:
      registry_password: ${{ secrets.ROBOTICS_ROBOTICSSTAGINGACR_PASSWORD }}
      registry_username: ${{ secrets.ROBOTICS_ROBOTICSSTAGINGACR_USERNAME }}

  deploy:
    name: Update deployment in Staging
    needs: build-and-push-latest-release-image-to-robotics-staging-registry
    uses: equinor/armada/.github/workflows/update_kubernetes_deployment.yml@main
    with:
      environment: staging
      registry: roboticsstagingacr.azurecr.io
      image_name: robotics/isar-robot
      tag: ${{ github.event.release.tag_name }}
      author_name: ${{ github.event.release.author.login }}
      infrastructure_repository: equinor/robotics-infrastructure
    secrets:
      deploy_key: ${{ secrets.ROBOTICS_INFRASTRUCTURE_DEPLOY_KEY }}
