name: Deploy to Development

# Only one workflow in a concurrency group may run at a time
concurrency:
  group: development-concurrency
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - "main"

jobs:
  trigger-github-deployment:
    name: Trigger GitHub Deployment
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Empty Step
        run: echo "Hello World"

  get-short-sha:
    needs: trigger-github-deployment
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - id: get-tag
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-8)
          echo "tag=$SHA_SHORT" >> "$GITHUB_OUTPUT"

  build-and-push-components:
    name: Build and push containers to ghcr for Development
    needs: [get-short-sha, trigger-github-deployment]
    uses: ./.github/workflows/publish_component.yml
    with:
      Registry: ghcr.io
      ImageName: ${{ github.repository }}
      # Add dev. prefix for the tags used in dev environment.
      # The commit hash can be interpreted as an integer if only numbers
      # when this tag later is written to a yaml file
      # PS: Needs to match deploy.with.Tag
      Tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      SecondaryTag: "dev"
    secrets:
      RegistryUsername: ${{ github.actor }}
      RegistryPassword: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Update deployment in Development
    needs: [build-and-push-components, get-short-sha, trigger-github-deployment]
    uses: ./.github/workflows/update_aurora_deployment.yml
    with:
      Environment: development
      Registry: ghcr.io
      ImageName: ${{ github.repository }}
      # Add dev. prefix for the tags used in dev environment. 
      # The commit hash can be interpreted as an integer if only numbers
      # when this tag later is written to a yaml file
      # PS: Needs to match build-and-push-components.with.Tag
      Tag: "dev.${{ needs.get-short-sha.outputs.tag }}"
      AuthorEmail: ${{ github.event.head_commit.author.email }}
      AuthorName: ${{ github.event.head_commit.author.name }}
    secrets:
      DeployKey: ${{ secrets.ROBOTICS_INFRASTRUCTURE_DEPLOY_KEY }}
